"""add weight tables

Revision ID: 365f3cda87b8
Revises: 397ef09bcd69
Create Date: 2026-05-15 07:45:42.496705
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '365f3cda87b8'
down_revision: Union[str, None] = '397ef09bcd69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_profiles_user_id'), 'weight_profiles', ['user_id'], unique=False)
    op.create_table('weight_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['weight_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_records_profile_id'), 'weight_records', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weight_records_profile_id'), table_name='weight_records')
    op.drop_table('weight_records')
    op.drop_index(op.f('ix_weight_profiles_user_id'), table_name='weight_profiles')
    op.drop_table('weight_profiles')
    # ### end Alembic commands ###
