"""add_recipe_price_links_media_type_orders

Revision ID: 397ef09bcd69
Revises: bdec0b94855b
Create Date: 2026-05-13 00:12:04.337709
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '397ef09bcd69'
down_revision: Union[str, None] = 'bdec0b94855b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('cart_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_recipe_id'), 'orders', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.add_column('media_files', sa.Column('media_type', sa.String(length=20), nullable=True))
    op.add_column('recipes', sa.Column('price', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('recipes', sa.Column('links', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'links')
    op.drop_column('recipes', 'price')
    op.drop_column('media_files', 'media_type')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_recipe_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
